function [result,acceptance] = b67_union_check_pack_v2(pack,xs,y,theta)
%B67_UNION_CHECK_PACK_V2 Deterministic checks of all 500 saved latent fields.
% Reuses the frozen direct-GP marginal/covariance checker for BOTH routes.
% No fitting, sampling, retry, file mutation, or change of numerical gates.
required={'F','fmu','fsd','g1','g2','xq','expr','hyp','mf','kind','info'};
assert(isstruct(pack) && isscalar(pack) && all(isfield(pack,required)), ...
    'b67union:checkPackSchema','Missing required sample-pack fields');
assert(ischar(pack.kind) && ismember(pack.kind,{'union','dense'}), ...
    'b67union:checkPackKind','kind must be union or dense');
NS=size(pack.F,2); ng=[numel(pack.g1),numel(pack.g2)]; q=prod(ng);
assert(NS==500,'b67union:checkPackCount','Formal checks require all 500 raw fields, including dense RQ');
assert((strcmp(pack.kind,'union') && (isequal(ng,[201 121]) || isequal(ng,[401 241]))) || ...
       (strcmp(pack.kind,'dense') && isequal(ng,[201 121])), ...
    'b67union:checkPackGrid','Unexpected formal query grid');
assert(isa(pack.fmu,'double') && isreal(pack.fmu) && isequal(size(pack.fmu),[q 1]) && ...
    all(isfinite(pack.fmu)) && isa(pack.fsd,'double') && isreal(pack.fsd) && ...
    isequal(size(pack.fsd),[q 1]) && all(isfinite(pack.fsd)), ...
    'b67union:checkPackMoments','Invalid analytic latent-field mean or standard deviation');
bad_sd=find(pack.fsd<=0,1);
if ~isempty(bad_sd)
    error('b67union:nonpositiveLatentVariance', ...
        'Original analytic latent SD is nonpositive at query row %d (SD=%.17g); no floor applied by this checker', ...
        bad_sd,pack.fsd(bad_sd));
end
assert(isa(pack.xq,'double') && isreal(pack.xq) && isequal(size(pack.xq),[q 2]) && ...
    all(isfinite(pack.xq(:))) && isa(xs,'double') && isreal(xs) && size(xs,2)==2 && ...
    all(isfinite(xs(:))) && isa(y,'double') && isreal(y) && isvector(y) && ...
    numel(y)==size(xs,1) && all(isfinite(y(:))), ...
    'b67union:checkPackCoordinates','Invalid training or query arrays');
% The checker and covariance point sets interpret F rows as x2-fastest.
a=unique(pack.xq(:,1)); b=unique(pack.xq(:,2)); [a2,b2]=meshgrid(a,b);
assert(numel(a)==ng(1) && numel(b)==ng(2) && isequal(pack.xq,[a2(:),b2(:)]), ...
    'b67union:checkPackOrder','Query rows do not follow the physical meshgrid order');
if isfield(pack,'theta')
    assert(isequal(pack.theta,theta),'b67union:checkPackThreshold','Saved and requested thresholds differ');
end
[wp,W]=b67_union_weakprop_v1(pack.F,pack.g1,pack.g2,theta);
if isfield(pack,'wp')
    assert(isequal(pack.wp(:),wp),'b67union:checkPackFunctional','Saved functional values disagree with raw fields');
end
pack.wp=wp; y=y(:);
k=sum(wp>0.10); p=k/NS;
z=1.959964; den=1+z^2/NS; center=p+z^2/(2*NS);
half=z*sqrt(p*(1-p)/NS+z^2/(4*NS^2));
Ewp=sum(W(:).*normcdf((theta-pack.fmu)./max(pack.fsd,1e-12)))/sum(W(:));
exp_gap=mean(wp)-Ewp; exp_mc_se=sqrt(var(wp)/NS);
mg=marginal_check_ski_v2(pack.expr,pack.hyp,pack.mf,xs,y,pack,theta);
result=struct('checker','b67_union_check_pack_v2','kind',pack.kind, ...
    'expr',pack.expr,'theta',theta,'event_threshold',0.10,'n_samples',NS, ...
    'query_grid',ng,'P',p,'mc_se',sqrt(p*(1-p)/NS), ...
    'wilson',[(center-half)/den,(center+half)/den],'k_of_N',[k NS], ...
    'wp_med',median(wp),'wp_iqr',iqr(wp),'wp_quantile_probabilities',[0.05 0.25 0.50 0.75 0.95], ...
    'wp_quantiles',prctile(wp,[5 25 50 75 95]),'wp_perfield',wp(:).', ...
    'expected_wp_pack',Ewp,'expected_wp_direct_reference',mean(wp)-mg.exp_gap, ...
    'exp_gap',exp_gap,'exp_mc_se',exp_mc_se,'spotcheck',mg,'spotcheck_pass',logical(mg.pass), ...
    'wp_note','Wilson interval covers Monte Carlo uncertainty conditional on fixed model, parameters, and grid.', ...
    'nested_done',false,'nested_query_grid',[],'nested_indices1',[],'nested_indices2',[], ...
    'wp_nested_perfield',[],'paired_delta_perfield',[],'paired_delta',struct(), ...
    'jitter_used',[],'jitter_var_rel_max',[],'sampler_timing',struct(), ...
    'union_axis_sizes',[],'union_nodes',[]);
% Retain actual sampler measurements; these are not new acceptance gates.
timing_names={'t_total','t_sample','t_samples_s','t_setup_s','total_elapsed_s','t_kernel','t_chol'};
for j=1:numel(timing_names)
    key=timing_names{j};
    if isfield(pack.info,key), result.sampler_timing.(key)=pack.info.(key); end
end
for key={'union_axis_sizes','union_nodes','jitter_var_rel_max'}
    if isfield(pack.info,key{1}), result.(key{1})=pack.info.(key{1}); end
end
% Fine union -> main; dense main -> coarse. These are SAME-field pairs.
if (strcmp(pack.kind,'union') && isequal(ng,[401 241])) || strcmp(pack.kind,'dense')
    i1=1:2:ng(1); i2=1:2:ng(2);
    Y=reshape(pack.F,ng(2),ng(1),NS); C=Y(i2,i1,:);
    wp_sub=b67_union_weakprop_v1(reshape(C,numel(i1)*numel(i2),NS), ...
        pack.g1(i1),pack.g2(i2),theta);
    delta=wp-wp_sub;
    result.nested_done=true; result.nested_query_grid=[numel(i1),numel(i2)];
    result.nested_indices1=i1; result.nested_indices2=i2;
    result.wp_nested_perfield=wp_sub(:).'; result.paired_delta_perfield=delta(:).';
    result.paired_delta=struct('med',median(delta),'maxabs',max(abs(delta)), ...
        'rms',sqrt(mean(delta.^2)),'note','Same realization, finer minus nested coarser quadrature; descriptive, no convergence gate.');
    if strcmp(pack.kind,'dense'), result.wp_sub_perfield=wp_sub(:).'; end
end
% The frozen checker records four sets, with err/(4*analytic MC scale)<=1.
sets_ok=iscell(mg.cov_sets) && numel(mg.cov_sets)==4;
if sets_ok
    expected_names={'center5x5','near_borehole25','far_borehole25','edge_strip25'};
    for j=1:4
        cs=mg.cov_sets{j};
        sets_ok=sets_ok && isfield(cs,'name') && strcmp(cs.name,expected_names{j}) && ...
            all(isfinite([cs.err,cs.mc_scale,cs.tol,cs.ratio])) && cs.ratio<=1;
    end
end
finite_metrics=all(isfinite([Ewp,exp_gap,exp_mc_se,mg.rms_mean,mg.max_abs_mean, ...
    mg.sd_ratio_med,mg.sd_ratio_q(:).',mg.exp_gap,mg.exp_mc_se,mg.cov_ratio_max]));
jitter_ok=true;
if strcmp(pack.kind,'dense')
    assert(isfield(pack.info,'jitter_used') && isnumeric(pack.info.jitter_used) && ...
        isreal(pack.info.jitter_used) && isscalar(pack.info.jitter_used) && ...
        isfinite(pack.info.jitter_used),'b67union:checkPackJitter','Dense jitter receipt is missing or nonfinite');
    result.jitter_used=pack.info.jitter_used;
    jitter_ok=pack.info.jitter_used>=0 && pack.info.jitter_used<=1e-8;
end
conditions=struct('all_500_fields',NS==500,'finite_metrics',finite_metrics, ...
    'mean_rms',mg.rms_mean<0.05,'sd_ratio_median',mg.sd_ratio_med>=0.95 && mg.sd_ratio_med<=1.05, ...
    'analytic_expectation_pack',abs(exp_gap)<=3*exp_mc_se, ...
    'analytic_expectation_direct',abs(mg.exp_gap)<=3*mg.exp_mc_se, ...
    'four_covariance_sets',logical(mg.cov_done) && sets_ok && mg.cov_ratio_max<=1, ...
    'frozen_marginal_checker',logical(mg.pass),'dense_jitter',jitter_ok);
keys=fieldnames(conditions); failed={};
for j=1:numel(keys)
    if ~conditions.(keys{j}), failed{end+1}=keys{j}; end %#ok<AGROW>
end
acceptance=struct('pass',isempty(failed),'conditions',conditions,'failure_reasons',{failed}, ...
    'thresholds',struct('mean_rms_strictly_less_than',0.05,'sd_ratio_median_range',[0.95 1.05], ...
        'expectation_mc_se_multiplier',3,'covariance_mc_scale_multiplier',4, ...
        'dense_jitter_max',1e-8,'required_samples',500), ...
    'nested_difference_is_descriptive',true,'retry_performed',false);
end
