function cfg = llm_api_config()
%LLM_API_CONFIG  Central configuration for LLM access (OpenRouter).
%
%   cfg = llm_api_config()
%
%   Returns a struct with:
%     .api_key   OpenRouter API key, read from the OPENROUTER_API_KEY
%                environment variable (never hard-code secrets in code)
%     .models    cell array of model slugs used for the multi-model panel
%     .tags      short display tags aligned with .models
%
%   Setup:
%     Windows (PowerShell):  $env:OPENROUTER_API_KEY = "sk-or-v1-..."
%     Linux/macOS:           export OPENROUTER_API_KEY="sk-or-v1-..."
%   or set it persistently in your OS environment, then start MATLAB.

    cfg.api_key = getenv('OPENROUTER_API_KEY');
    if isempty(cfg.api_key)
        error(['llm_api_config:noKey  Set the OPENROUTER_API_KEY ', ...
               'environment variable before running LLM-dependent scripts.']);
    end

    % A diverse panel for cross-model robustness: 5 inexpensive mid-tier
    % models + 3 flagship anchors (capability-tier ablation).
    cfg.models = { ...
        'openai/gpt-4o-mini', ...
        'anthropic/claude-3.5-haiku', ...
        'google/gemini-2.5-flash', ...
        'deepseek/deepseek-chat-v3.1', ...
        'meta-llama/llama-3.3-70b-instruct', ...
        'openai/gpt-5.5', ...
        'anthropic/claude-opus-4.8', ...
        'google/gemini-3.1-pro-preview' };

    cfg.tags = { ...
        'gpt-4o-mini', ...
        'claude-3.5-haiku', ...
        'gemini-2.5-flash', ...
        'deepseek-v3.1', ...
        'llama-3.3-70b', ...
        'gpt-5.5', ...
        'claude-opus-4.8', ...
        'gemini-3.1-pro' };
end
